defaults: &defaults
  working_directory: ~/unsullied-api
  docker:
    - image: node:10
      environment:
        NODE_ENV: test

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: yarn run coverage

      - store_artifacts:
          path: coverage
  deploy-branch:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          name: Deploy to Heroku
          command: |
            ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
            git push git@heroku.com:staging-unsullied-api.git $CIRCLE_SHA1:refs/heads/master -f
  deploy-tag:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          name: Deploy to Heroku
          command: |
            ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
            git push git@heroku.com:unsullied-api.git $CIRCLE_SHA1:refs/heads/master -f
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy-branch:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - deploy-tag:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
